# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=57678


// Add a new address 
POST {{host}}:{{port}}/Address
Content-Type: application/json

{
  "Data": {
   "AddressLine1": "Test 1", 
   "AddressLine2": "Test 2"
  }
}
