global using System.Reflection;
global using Ardalis.SharedKernel;
global using FastEndpoints;
global using FastEndpoints.Swagger;
global using MediatR;
global using Platy.AdventureWorks.Repository;
global using Platy.AdventureWorks.Logging;
global using Platy.AdventureWorks.RestApi.Configurations;
global using Microsoft.Extensions.DependencyInjection;
